# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
TODO
"""

import json
import os
from collections import defaultdict

import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import seaborn as sns
from matplotlib.lines import Line2D

# Content configuration
EVAL_FOLDER = "./eval"
TASKS = ["math", "gsm8k", "dapo-with-aime24"]
SEEDS = [41, 42, 43]
ALGORITHMS = ["grpo", "elliptical", "untrained", "unlikely"]
CHECKPOINT_TYPE = "best_pass@1"
LOG_AXES = False

# Plot configuration
FACE_COLOR = "#F7F7FF"
MARKER = "o"
LINEWIDTH = 1.275
MARKERSIZE = 6
MARKEREDGEWIDTH = 0.9
LABEL_FONT_SIZE = 10
TITLE_FONT_SIZE = 11
TICK_LABEL_FONT_SIZE = 8
LEGEND_FONT_SIZE = 8

TASK_TO_NICE_NAME = {
    "math": "MATH",
    "gsm8k": "GSM8K",
    "dapo-with-aime24": "AIME 2024",
    "countdown-4": "Countdown",
}

ALGO_TO_COLOR = {
    "grpo": sns.color_palette("deep")[-1],
    "untrained": sns.color_palette("deep")[7],
    "elliptical": sns.color_palette("colorblind")[2],
    "unlikely": sns.color_palette("deep")[1],
}

ALGO_TO_NICE_NAME = {
    "grpo": "GRPO",
    "untrained": "Base Model",
    "elliptical": r"RepExp (ours)",
    "unlikely": "Unlikeliness",
}

TASK_ALGO_TO_MARKER_DELTA = {
    "math": {
        "grpo": -0.05,
        "unlikely": -0.1,
    },
    "dapo-with-aime24": {
        "grpo": -0.17,
        "unlikely": -0.15,
    },
    "countdown-4": {
        "grpo": -0.05,
        "unlikely": -0.05,
    },
    "gsm8k": {
        "grpo": -0.03,
        "unlikely": -0.02,
    },
}

TASK_TO_MOVE_UP = {
    "math": 0.004,
    "gsm8k": 0.002,
    "dapo-with-aime24": 0.008,
    "countdown-4": 0.008,
}


def process_data(data: list[dict[str, float]], algorithm: str) -> tuple[dict[int, float], dict[int, float]]:
    """
    Process the pass@k data generated by a given algorithm.

    Args:
        data (List[Dict]): The data to process.
        algorithm (str): Algorithm that generated the data.

    Returns:
        Tuple[Dict[int, float], Dict[int, float]]:
            pass_at_k - The mean pass@k values.
            pass_at_k_sem - The standard error of the pass@k values.
    """
    pass_at_k = defaultdict(list)
    for d in data:
        for key, v in d.items():
            for k in [1, 2, 4, 8, 16, 32, 64, 128, 256]:
                if key.endswith(f"reward/pass@{k}/mean"):
                    pass_at_k[k].append(v)

    # NOTE: we only use a single seed for untrained since there is only one checkpoint for it
    if algorithm != "untrained":
        for k in pass_at_k.keys():
            assert len(pass_at_k[k]) == len(SEEDS)

    pass_at_k_sem = {k: stats.sem(v) for k, v in pass_at_k.items()} if algorithm != "untrained" else None
    pass_at_k = {k: np.mean(v) for k, v in pass_at_k.items()}

    return pass_at_k, pass_at_k_sem


def plot_arrow(
    ax: plt.Axes,
    method_1_xs: np.ndarray,
    method_1_ys: np.ndarray,
    elliptical_ys: np.ndarray,
    color: str,
    y_min: float,
    task: str,
    algo: str,
    marker_delta: float = 0.0,
) -> None:
    """
    Draws a double-headed arrow between elliptical and a given baseline (method_1)
    at the pass@256 (i.e. the last y-value). Also annotates the sample efficiency improvement.

    Args:
        ax (plt.Axes): The matplotlib axis to draw on.
        method_1_xs (np.ndarray): X values for the first method (e.g., 'unlikely' or 'grpo').
        method_1_ys (np.ndarray): Y values for the first method (e.g., 'unlikely' or 'grpo').
        elliptical_ys (np.ndarray): Y values for elliptical.
        color (str): The color for the arrow and text.
        y_min (float): The y-value at which to start drawing the vertical lines.
        task (str): The task name.
        algo (str): Algorithm name (i.e., 'unlikely' or 'grpo').
        marker_delta (float, optional): Small vertical offset for drawing the arrow & text, default 0.0.
    """
    y_min_overlap = max(method_1_ys.min(), elliptical_ys.min())
    y_max_overlap = min(method_1_ys.max(), elliptical_ys.max())

    y_grid = np.linspace(y_min_overlap, y_max_overlap, 400)
    x_method_1_at_y = np.interp(y_grid, method_1_ys, method_1_xs)
    x_elliptical_at_y = np.interp(y_grid, elliptical_ys, method_1_xs)

    # NOTE: uncomment the following if you want to use the y value for which the x-axis are the furthest apart
    # dx_log = np.abs(np.log2(x_elliptical_at_y) - np.log2(x_method_1_at_y))
    # max_idx = int(np.argmax(dx_log))

    # Just take the last y_value, and find the corresponding x-values
    # for both methods
    max_idx = -1
    y_star = y_grid[max_idx]
    x_random_star = x_method_1_at_y[max_idx]
    x_elliptical_star = x_elliptical_at_y[max_idx]

    # Draw double-headed arrow between the two x positions at y_star
    ax.annotate(
        "",
        xy=(x_random_star, y_star + marker_delta),
        xytext=(x_elliptical_star, y_star + marker_delta),
        arrowprops=dict(arrowstyle="<->", color=color, lw=1.2),
    )

    # Place a small label at the center of the arrow
    if LOG_AXES:
        # Take geometric mean to look centered on a log axis
        mid_x = np.sqrt(x_random_star * x_elliptical_star)
    else:
        # Take average to look centered on a linear axis
        mid_x = (x_random_star + x_elliptical_star) / 2

    ax.text(
        mid_x,
        y_star + marker_delta + TASK_TO_MOVE_UP[task],
        r"$\mathbf{\times" + f"{(x_random_star / x_elliptical_star):.1f}" + "}$",
        color=color,
        ha="center",
        va="bottom",
        fontsize=8,
    )

    print(
        f"On {TASK_TO_NICE_NAME[task]}, the pass@{int(round(x_elliptical_star))} for elliptical \
        is equivalent to the pass@{int(round(x_random_star))} for {algo}"
    )

    # Draw vertical lines at x_random_star & x_elliptical_star, up to y_star
    if marker_delta != 0:
        # NOTE: We shift slightly by 3 or 2 units to make sure the unlikely and grpo lines don't completely overlap
        if LOG_AXES:
            ax.vlines(
                x_random_star + (3 if algo == "unlikely" else -3),
                ymin=y_min,
                ymax=y_star,
                color=color,
                linestyle="dashed",
                linewidth=1.0,
            )
        else:
            ax.vlines(
                x_random_star + (2 if algo == "unlikely" else -2),
                ymin=y_min,
                ymax=y_star,
                color=color,
                linestyle="dashed",
                linewidth=1.0,
            )
        ax.vlines(x_elliptical_star, ymin=y_min, ymax=y_star, color=color, linestyle="dashed", linewidth=1.0)


def main():
    # Get all top-level folders in EVAL_FOLDER
    eval_folders = os.listdir(EVAL_FOLDER)

    # Figure setup
    sns.set_style("whitegrid")
    fig, axs = plt.subplots(1, 3, figsize=(9, 3))

    for i, (ax, task) in enumerate(zip(axs, TASKS, strict=False)):
        algo_to_xs = {}
        algo_to_ys = {}

        for algorithm in ALGORITHMS:
            # Get all eval folders for the current task and algorithm
            folders = [f for f in eval_folders if task in f and algorithm in f]
            if len(folders) == 0:
                continue

            data = []
            for folder in folders:
                if algorithm == "untrained":
                    with open(os.path.join(EVAL_FOLDER, folder, "eval.json")) as f:
                        data.append(json.load(f))
                else:
                    with open(os.path.join(EVAL_FOLDER, folder, CHECKPOINT_TYPE, "eval.json")) as f:
                        data.append(json.load(f))

            pass_at_k, pass_at_k_sem = process_data(data, algorithm)

            xs = np.array(list(pass_at_k.keys()))
            ys = np.array([pass_at_k[k] for k in xs])
            algo_to_xs[algorithm] = xs
            algo_to_ys[algorithm] = ys

            # Plot the current task - algorithm data
            ax.plot(
                xs,
                ys,
                color=ALGO_TO_COLOR[algorithm],
                label=algorithm,
                markeredgecolor=FACE_COLOR,
                marker=MARKER,
                linewidth=LINEWIDTH,
                markersize=MARKERSIZE,
                markeredgewidth=MARKEREDGEWIDTH,
                alpha=1.0 if algorithm != "untrained" else 0.8,
            )

            # Plot the standard error in shaded bands
            if algorithm != "untrained":
                sems = np.array([pass_at_k_sem[k] for k in xs])
                ax.fill_between(xs, ys - sems, ys + sems, alpha=0.2, color=ALGO_TO_COLOR[algorithm])

            # Set y-axis limits
            if task == "math":
                y_min = 0.7
                ax.set_ylim(top=0.95, bottom=y_min)
            elif task == "gsm8k":
                y_min = 0.925
                ax.set_ylim(top=0.995, bottom=y_min)
            elif task == "dapo-with-aime24":
                y_min = 0.1
                ax.set_ylim(bottom=y_min, top=0.63)

            # Set x-axis limits
            if LOG_AXES:
                ax.set_xlim(left=2 ** (-0.2), right=2 ** (8.2))
            else:
                ax.set_xlim(left=-10, right=266)

            # Set x-axis scale and ticks
            if LOG_AXES:
                ax.set_xscale("log", base=2)
                x_ticks = [2**i for i in range(int(np.log2(max(xs))) + 1)]
                x_tick_labels = [f"$2^{{{i}}}$" for i in range(int(np.log2(max(xs))) + 1)]
            else:
                # set every 64
                x_ticks = [1, 32, 64, 96, 128, 160, 192, 224, 256]
                x_tick_labels = ["1", "32", "64", "96", "128", "160", "192", "224", "256"]
            ax.set_xticks(x_ticks, x_tick_labels)

            # Set axes labels
            ax.set_xlabel("k", fontsize=LABEL_FONT_SIZE)
            if i == 0:
                ax.set_ylabel("Pass@k", fontsize=LABEL_FONT_SIZE)

            # Set title
            ax.set_title(f"{TASK_TO_NICE_NAME[task]}", fontsize=TITLE_FONT_SIZE)

        # Set font size for tick labels
        for _label in ax.get_xticklabels():
            _label.set_fontsize(TICK_LABEL_FONT_SIZE)
        for _label in ax.get_yticklabels():
            _label.set_fontsize(TICK_LABEL_FONT_SIZE)

        # Plot arrow comparison with GRPO
        if "grpo" in ALGORITHMS:
            plot_arrow(
                ax,
                algo_to_xs["grpo"],
                algo_to_ys["grpo"],
                algo_to_ys["elliptical"],
                ALGO_TO_COLOR["grpo"],
                y_min,
                marker_delta=TASK_ALGO_TO_MARKER_DELTA[task]["grpo"],
                task=task,
                algo="grpo",
            )

        # Plot arrow comparison with unlikely
        if "unlikely" in ALGORITHMS:
            plot_arrow(
                ax,
                algo_to_xs["unlikely"],
                algo_to_ys["unlikely"],
                algo_to_ys["elliptical"],
                ALGO_TO_COLOR["unlikely"],
                y_min,
                marker_delta=TASK_ALGO_TO_MARKER_DELTA[task]["unlikely"],
                task=task,
                algo="unlikely",
            )

    # Create legend handles
    legend_handles = [
        Line2D(
            [0],
            [0],
            color=ALGO_TO_COLOR[algo],
            marker=MARKER,
            linestyle="-",
            linewidth=LINEWIDTH,
            markersize=MARKERSIZE,
            markeredgewidth=MARKEREDGEWIDTH,
            markeredgecolor=FACE_COLOR,
            label=ALGO_TO_NICE_NAME[algo],
        )
        for algo in ALGORITHMS
    ]

    # Create legend
    legend = fig.legend(
        handles=legend_handles,
        loc="lower center",
        ncol=len(ALGORITHMS),
        bbox_to_anchor=(0.5, -0.07),
        fontsize=LEGEND_FONT_SIZE,
    )

    plt.tight_layout()

    # Save figure
    plt.savefig(
        os.path.join("figures", f"rl_pass_at_k_{TASKS}_{CHECKPOINT_TYPE}{'' if LOG_AXES else '_linear_axes'}.pdf"),
        bbox_extra_artists=(legend,),
        bbox_inches="tight",
    )

    # Close figure
    plt.close()


if __name__ == "__main__":
    main()
