mv checkpoints/llm-exploration-rl-training/gsm8k_elliptical_seed_41_kl_0.0_ppo_epochs_1_beta_0.01_turn_off_elliptical_if_none_correct_True_sparse_dim_128 /scratch/gpfs/PLI/jtuyls/checkpoints/llm-exploration-rl-training/
mv checkpoints/llm-exploration-rl-training/gsm8k_elliptical_seed_42_kl_0.0_ppo_epochs_1_beta_0.01_turn_off_elliptical_if_none_correct_True_sparse_dim_128 /scratch/gpfs/PLI/jtuyls/checkpoints/llm-exploration-rl-training/
mv checkpoints/llm-exploration-rl-training/gsm8k_elliptical_seed_43_kl_0.0_ppo_epochs_1_beta_0.01_turn_off_elliptical_if_none_correct_True_sparse_dim_128 /scratch/gpfs/PLI/jtuyls/checkpoints/llm-exploration-rl-training/

mv checkpoints/llm-exploration-rl-training/math_elliptical_seed_41_kl_0.0_ppo_epochs_1_beta_0.01_turn_off_elliptical_if_none_correct_True_sparse_dim_128 /scratch/gpfs/PLI/jtuyls/checkpoints/llm-exploration-rl-training/
mv checkpoints/llm-exploration-rl-training/math_elliptical_seed_42_kl_0.0_ppo_epochs_1_beta_0.01_turn_off_elliptical_if_none_correct_True_sparse_dim_128 /scratch/gpfs/PLI/jtuyls/checkpoints/llm-exploration-rl-training/
mv checkpoints/llm-exploration-rl-training/math_elliptical_seed_43_kl_0.0_ppo_epochs_1_beta_0.01_turn_off_elliptical_if_none_correct_True_sparse_dim_128 /scratch/gpfs/PLI/jtuyls/checkpoints/llm-exploration-rl-training/
